sudo: false
language: go
go:
  - 1.7
before_script:
  - go get -u github.com/golang/lint/golint
script:
  - go test -race ./...
after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...
os:
  - linux
notifications:
  email: false
